INSERT INTO SPORT(LABEL, DESCRIPTION, ACTIVE) VALUES ('bball', 'bball', true);
INSERT INTO SPORT(LABEL, DESCRIPTION, ACTIVE) VALUES ('fball', 'bball', true);
INSERT INTO SPORT(LABEL, DESCRIPTION, ACTIVE) VALUES ('sball', 'bball', true);
