/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubImage extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.ClubImageRecord> {

	private static final long serialVersionUID = -392580686;

	/**
	 * The singleton instance of <code>public.club_image</code>
	 */
	public static final com.currant.jooq.tables.ClubImage CLUB_IMAGE = new com.currant.jooq.tables.ClubImage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.ClubImageRecord> getRecordType() {
		return com.currant.jooq.tables.records.ClubImageRecord.class;
	}

	/**
	 * The column <code>public.club_image.club_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubImageRecord, java.lang.Long> CLUB_ID = createField("club_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.club_image.image_url</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubImageRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>public.club_image.sort_order</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubImageRecord, java.lang.Integer> SORT_ORDER = createField("sort_order", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.club_image</code> table reference
	 */
	public ClubImage() {
		super("club_image", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.club_image</code> table reference
	 */
	public ClubImage(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.ClubImage.CLUB_IMAGE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubImageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubImageRecord>>asList(com.currant.jooq.Keys.CLUB_IMAGE_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubImageRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubImageRecord, ?>>asList(com.currant.jooq.Keys.CLUB_IMAGE__CLUB_IMAGE_CLUB_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.ClubImage as(java.lang.String alias) {
		return new com.currant.jooq.tables.ClubImage(alias);
	}
}
