/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubWallPost extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.ClubWallPostRecord> {

	private static final long serialVersionUID = 2139343205;

	/**
	 * The singleton instance of <code>public.club_wall_post</code>
	 */
	public static final com.currant.jooq.tables.ClubWallPost CLUB_WALL_POST = new com.currant.jooq.tables.ClubWallPost();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.ClubWallPostRecord> getRecordType() {
		return com.currant.jooq.tables.records.ClubWallPostRecord.class;
	}

	/**
	 * The column <code>public.club_wall_post.club_wall_post_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.Long> CLUB_WALL_POST_ID = createField("club_wall_post_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.club_wall_post.author_profile_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.Long> AUTHOR_PROFILE_ID = createField("author_profile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.club_wall_post.club_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.Long> CLUB_ID = createField("club_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.club_wall_post.text</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>public.club_wall_post.image_url</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>public.club_wall_post.created</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubWallPostRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>public.club_wall_post.parent_post_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.Long> PARENT_POST_ID = createField("parent_post_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>public.club_wall_post</code> table reference
	 */
	public ClubWallPost() {
		super("club_wall_post", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.club_wall_post</code> table reference
	 */
	public ClubWallPost(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.Long> getIdentity() {
		return com.currant.jooq.Keys.IDENTITY_CLUB_WALL_POST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubWallPostRecord> getPrimaryKey() {
		return com.currant.jooq.Keys.CLUB_WALL_POST_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubWallPostRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubWallPostRecord>>asList(com.currant.jooq.Keys.CLUB_WALL_POST_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubWallPostRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubWallPostRecord, ?>>asList(com.currant.jooq.Keys.CLUB_WALL_POST__CLUB_WALL_POST_AUTHOR_PROFILE_ID_FKEY, com.currant.jooq.Keys.CLUB_WALL_POST__CLUB_WALL_POST_CLUB_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.ClubWallPost as(java.lang.String alias) {
		return new com.currant.jooq.tables.ClubWallPost(alias);
	}
}
