/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubIcon extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.ClubIconRecord> {

	private static final long serialVersionUID = 55443393;

	/**
	 * The singleton instance of <code>public.club_icon</code>
	 */
	public static final com.currant.jooq.tables.ClubIcon CLUB_ICON = new com.currant.jooq.tables.ClubIcon();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.ClubIconRecord> getRecordType() {
		return com.currant.jooq.tables.records.ClubIconRecord.class;
	}

	/**
	 * The column <code>public.club_icon.club_icon_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubIconRecord, java.lang.Long> CLUB_ICON_ID = createField("club_icon_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.club_icon.image_url</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubIconRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>public.club_icon.locked</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubIconRecord, java.lang.Boolean> LOCKED = createField("locked", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.club_icon</code> table reference
	 */
	public ClubIcon() {
		super("club_icon", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.club_icon</code> table reference
	 */
	public ClubIcon(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.ClubIcon.CLUB_ICON);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.currant.jooq.tables.records.ClubIconRecord, java.lang.Long> getIdentity() {
		return com.currant.jooq.Keys.IDENTITY_CLUB_ICON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubIconRecord> getPrimaryKey() {
		return com.currant.jooq.Keys.CLUB_ICON_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubIconRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubIconRecord>>asList(com.currant.jooq.Keys.CLUB_ICON_PKEY, com.currant.jooq.Keys.CLUB_ICON_IMAGE_URL_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.ClubIcon as(java.lang.String alias) {
		return new com.currant.jooq.tables.ClubIcon(alias);
	}
}
