/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Club extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.ClubRecord> {

	private static final long serialVersionUID = -432921524;

	/**
	 * The singleton instance of <code>public.club</code>
	 */
	public static final com.currant.jooq.tables.Club CLUB = new com.currant.jooq.tables.Club();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.ClubRecord> getRecordType() {
		return com.currant.jooq.tables.records.ClubRecord.class;
	}

	/**
	 * The column <code>public.club.club_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.Long> CLUB_ID = createField("club_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.club.label</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(30), this);

	/**
	 * The column <code>public.club.description</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>public.club.location</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>public.club.gps_coordinates</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.String> GPS_COORDINATES = createField("gps_coordinates", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>public.club.club_icon</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.Long> CLUB_ICON = createField("club_icon", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.club.club_icon_back_color</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.Integer> CLUB_ICON_BACK_COLOR = createField("club_icon_back_color", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.club.club_icon_front_color</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.Integer> CLUB_ICON_FRONT_COLOR = createField("club_icon_front_color", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.club.visibility</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.String> VISIBILITY = createField("visibility", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>public.club.open_enrollment</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.Boolean> OPEN_ENROLLMENT = createField("open_enrollment", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * The column <code>public.club.status</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>public.club.byof</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ClubRecord, java.lang.Boolean> BYOF = createField("byof", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.club</code> table reference
	 */
	public Club() {
		super("club", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.club</code> table reference
	 */
	public Club(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.Club.CLUB);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.currant.jooq.tables.records.ClubRecord, java.lang.Long> getIdentity() {
		return com.currant.jooq.Keys.IDENTITY_CLUB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubRecord> getPrimaryKey() {
		return com.currant.jooq.Keys.CLUB_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubRecord>>asList(com.currant.jooq.Keys.CLUB_PKEY, com.currant.jooq.Keys.CLUB_LABEL_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.Club as(java.lang.String alias) {
		return new com.currant.jooq.tables.Club(alias);
	}
}
