/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Connection extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.ConnectionRecord> {

	private static final long serialVersionUID = -909109887;

	/**
	 * The singleton instance of <code>public.connection</code>
	 */
	public static final com.currant.jooq.tables.Connection CONNECTION = new com.currant.jooq.tables.Connection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.ConnectionRecord> getRecordType() {
		return com.currant.jooq.tables.records.ConnectionRecord.class;
	}

	/**
	 * The column <code>public.connection.source_profile_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ConnectionRecord, java.lang.Long> SOURCE_PROFILE_ID = createField("source_profile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.connection.target_profile_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ConnectionRecord, java.lang.Long> TARGET_PROFILE_ID = createField("target_profile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.connection.status</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ConnectionRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * Create a <code>public.connection</code> table reference
	 */
	public Connection() {
		super("connection", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.connection</code> table reference
	 */
	public Connection(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.Connection.CONNECTION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.ConnectionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.ConnectionRecord>>asList(com.currant.jooq.Keys.CONNECTION_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.ConnectionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.ConnectionRecord, ?>>asList(com.currant.jooq.Keys.CONNECTION__CONNECTION_SOURCE_PROFILE_ID_FKEY, com.currant.jooq.Keys.CONNECTION__CONNECTION_TARGET_PROFILE_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.Connection as(java.lang.String alias) {
		return new com.currant.jooq.tables.Connection(alias);
	}
}
