/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrantUser extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.CurrantUserRecord> {

	private static final long serialVersionUID = -1729530812;

	/**
	 * The singleton instance of <code>public.currant_user</code>
	 */
	public static final com.currant.jooq.tables.CurrantUser CURRANT_USER = new com.currant.jooq.tables.CurrantUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.CurrantUserRecord> getRecordType() {
		return com.currant.jooq.tables.records.CurrantUserRecord.class;
	}

	/**
	 * The column <code>public.currant_user.currant_user_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.Long> CURRANT_USER_ID = createField("currant_user_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.currant_user.email_address</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.String> EMAIL_ADDRESS = createField("email_address", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>public.currant_user.salt</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.String> SALT = createField("salt", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>public.currant_user.password</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>public.currant_user.account_status</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.String> ACCOUNT_STATUS = createField("account_status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>public.currant_user.subscriber_type</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.String> SUBSCRIBER_TYPE = createField("subscriber_type", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>public.currant_user.active</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.currant_user</code> table reference
	 */
	public CurrantUser() {
		super("currant_user", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.currant_user</code> table reference
	 */
	public CurrantUser(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.CurrantUser.CURRANT_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.Long> getIdentity() {
		return com.currant.jooq.Keys.IDENTITY_CURRANT_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.currant.jooq.tables.records.CurrantUserRecord> getPrimaryKey() {
		return com.currant.jooq.Keys.CURRANT_USER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.CurrantUserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.CurrantUserRecord>>asList(com.currant.jooq.Keys.CURRANT_USER_PKEY, com.currant.jooq.Keys.USER_EMAIL_ADDRESS_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.CurrantUser as(java.lang.String alias) {
		return new com.currant.jooq.tables.CurrantUser(alias);
	}
}
