/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Equipment extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.EquipmentRecord> {

	private static final long serialVersionUID = 1483113994;

	/**
	 * The singleton instance of <code>public.equipment</code>
	 */
	public static final com.currant.jooq.tables.Equipment EQUIPMENT = new com.currant.jooq.tables.Equipment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.EquipmentRecord> getRecordType() {
		return com.currant.jooq.tables.records.EquipmentRecord.class;
	}

	/**
	 * The column <code>public.equipment.equipment_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.EquipmentRecord, java.lang.Long> EQUIPMENT_ID = createField("equipment_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.equipment.label</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.EquipmentRecord, java.lang.String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(30), this);

	/**
	 * The column <code>public.equipment.description</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.EquipmentRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>public.equipment.image_url</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.EquipmentRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>public.equipment.active</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.EquipmentRecord, java.lang.Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.equipment</code> table reference
	 */
	public Equipment() {
		super("equipment", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.equipment</code> table reference
	 */
	public Equipment(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.Equipment.EQUIPMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.currant.jooq.tables.records.EquipmentRecord, java.lang.Long> getIdentity() {
		return com.currant.jooq.Keys.IDENTITY_EQUIPMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.currant.jooq.tables.records.EquipmentRecord> getPrimaryKey() {
		return com.currant.jooq.Keys.EQUIPMENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.EquipmentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.EquipmentRecord>>asList(com.currant.jooq.Keys.EQUIPMENT_PKEY, com.currant.jooq.Keys.EQUIPMENT_LABEL_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.Equipment as(java.lang.String alias) {
		return new com.currant.jooq.tables.Equipment(alias);
	}
}
