/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.GameRecord> {

	private static final long serialVersionUID = 1703216488;

	/**
	 * The singleton instance of <code>public.game</code>
	 */
	public static final com.currant.jooq.tables.Game GAME = new com.currant.jooq.tables.Game();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.GameRecord> getRecordType() {
		return com.currant.jooq.tables.records.GameRecord.class;
	}

	/**
	 * The column <code>public.game.game_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game.sport_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Long> SPORT_ID = createField("sport_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game.visibility</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> VISIBILITY = createField("visibility", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>public.game.club_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Long> CLUB_ID = createField("club_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game.location</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>public.game.gps_coordinates</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> GPS_COORDINATES = createField("gps_coordinates", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>public.game.byof</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Boolean> BYOF = createField("byof", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * The column <code>public.game.game_time</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.sql.Timestamp> GAME_TIME = createField("game_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>public.game.size</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.game.intensity</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> INTENSITY = createField("intensity", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>public.game.description</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>public.game.status</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>public.game.image_url</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this);

	/**
	 * The column <code>public.game.active</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * The column <code>public.game.min_players</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Integer> MIN_PLAYERS = createField("min_players", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.game.max_players</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.Integer> MAX_PLAYERS = createField("max_players", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.game.waitlist_strategy</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameRecord, java.lang.String> WAITLIST_STRATEGY = createField("waitlist_strategy", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * Create a <code>public.game</code> table reference
	 */
	public Game() {
		super("game", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.game</code> table reference
	 */
	public Game(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.Game.GAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.currant.jooq.tables.records.GameRecord, java.lang.Long> getIdentity() {
		return com.currant.jooq.Keys.IDENTITY_GAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.currant.jooq.tables.records.GameRecord> getPrimaryKey() {
		return com.currant.jooq.Keys.GAME_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameRecord>>asList(com.currant.jooq.Keys.GAME_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameRecord, ?>>asList(com.currant.jooq.Keys.GAME__GAME_SPORT_ID_FKEY, com.currant.jooq.Keys.GAME__GAME_CLUB_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.Game as(java.lang.String alias) {
		return new com.currant.jooq.tables.Game(alias);
	}
}
