/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameEquipment extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.GameEquipmentRecord> {

	private static final long serialVersionUID = 832793787;

	/**
	 * The singleton instance of <code>public.game_equipment</code>
	 */
	public static final com.currant.jooq.tables.GameEquipment GAME_EQUIPMENT = new com.currant.jooq.tables.GameEquipment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.GameEquipmentRecord> getRecordType() {
		return com.currant.jooq.tables.records.GameEquipmentRecord.class;
	}

	/**
	 * The column <code>public.game_equipment.game_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameEquipmentRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game_equipment.equipment_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameEquipmentRecord, java.lang.Long> EQUIPMENT_ID = createField("equipment_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game_equipment.amount</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameEquipmentRecord, java.lang.Integer> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.game_equipment.claimed</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameEquipmentRecord, java.lang.Boolean> CLAIMED = createField("claimed", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * The column <code>public.game_equipment.claimed_by_profile_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameEquipmentRecord, java.lang.Long> CLAIMED_BY_PROFILE_ID = createField("claimed_by_profile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game_equipment.sort_order</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameEquipmentRecord, java.lang.Integer> SORT_ORDER = createField("sort_order", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.game_equipment</code> table reference
	 */
	public GameEquipment() {
		super("game_equipment", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.game_equipment</code> table reference
	 */
	public GameEquipment(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameEquipmentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameEquipmentRecord>>asList(com.currant.jooq.Keys.GAME_EQUIPMENT_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, ?>>asList(com.currant.jooq.Keys.GAME_EQUIPMENT__GAME_EQUIPMENT_GAME_ID_FKEY, com.currant.jooq.Keys.GAME_EQUIPMENT__GAME_EQUIPMENT_EQUIPMENT_ID_FKEY, com.currant.jooq.Keys.GAME_EQUIPMENT__GAME_EQUIPMENT_CLAIMED_BY_PROFILE_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.GameEquipment as(java.lang.String alias) {
		return new com.currant.jooq.tables.GameEquipment(alias);
	}
}
