/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameProfileStarred extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.GameProfileStarredRecord> {

	private static final long serialVersionUID = -1679334497;

	/**
	 * The singleton instance of <code>public.game_profile_starred</code>
	 */
	public static final com.currant.jooq.tables.GameProfileStarred GAME_PROFILE_STARRED = new com.currant.jooq.tables.GameProfileStarred();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.GameProfileStarredRecord> getRecordType() {
		return com.currant.jooq.tables.records.GameProfileStarredRecord.class;
	}

	/**
	 * The column <code>public.game_profile_starred.game_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameProfileStarredRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game_profile_starred.profile_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameProfileStarredRecord, java.lang.Long> PROFILE_ID = createField("profile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>public.game_profile_starred</code> table reference
	 */
	public GameProfileStarred() {
		super("game_profile_starred", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.game_profile_starred</code> table reference
	 */
	public GameProfileStarred(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileStarredRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileStarredRecord>>asList(com.currant.jooq.Keys.GAME_PROFILE_STARRED_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileStarredRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileStarredRecord, ?>>asList(com.currant.jooq.Keys.GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_GAME_ID_FKEY, com.currant.jooq.Keys.GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_PROFILE_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.GameProfileStarred as(java.lang.String alias) {
		return new com.currant.jooq.tables.GameProfileStarred(alias);
	}
}
