/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameProfileConnection extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.GameProfileConnectionRecord> {

	private static final long serialVersionUID = 637288409;

	/**
	 * The singleton instance of <code>public.game_profile_connection</code>
	 */
	public static final com.currant.jooq.tables.GameProfileConnection GAME_PROFILE_CONNECTION = new com.currant.jooq.tables.GameProfileConnection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.GameProfileConnectionRecord> getRecordType() {
		return com.currant.jooq.tables.records.GameProfileConnectionRecord.class;
	}

	/**
	 * The column <code>public.game_profile_connection.game_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameProfileConnectionRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game_profile_connection.profile_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameProfileConnectionRecord, java.lang.Long> PROFILE_ID = createField("profile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.game_profile_connection.status</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.GameProfileConnectionRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * Create a <code>public.game_profile_connection</code> table reference
	 */
	public GameProfileConnection() {
		super("game_profile_connection", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.game_profile_connection</code> table reference
	 */
	public GameProfileConnection(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileConnectionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileConnectionRecord>>asList(com.currant.jooq.Keys.GAME_PROFILE_CONNECTION_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileConnectionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileConnectionRecord, ?>>asList(com.currant.jooq.Keys.GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_GAME_ID_FKEY, com.currant.jooq.Keys.GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_PROFILE_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.GameProfileConnection as(java.lang.String alias) {
		return new com.currant.jooq.tables.GameProfileConnection(alias);
	}
}
