/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileSport extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.ProfileSportRecord> {

	private static final long serialVersionUID = 1692026982;

	/**
	 * The singleton instance of <code>public.profile_sport</code>
	 */
	public static final com.currant.jooq.tables.ProfileSport PROFILE_SPORT = new com.currant.jooq.tables.ProfileSport();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.ProfileSportRecord> getRecordType() {
		return com.currant.jooq.tables.records.ProfileSportRecord.class;
	}

	/**
	 * The column <code>public.profile_sport.profile_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ProfileSportRecord, java.lang.Long> PROFILE_ID = createField("profile_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.profile_sport.sport_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ProfileSportRecord, java.lang.Long> SPORT_ID = createField("sport_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.profile_sport.sort_order</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.ProfileSportRecord, java.lang.Integer> SORT_ORDER = createField("sort_order", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.profile_sport</code> table reference
	 */
	public ProfileSport() {
		super("profile_sport", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.profile_sport</code> table reference
	 */
	public ProfileSport(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.ProfileSport.PROFILE_SPORT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.ProfileSportRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.ProfileSportRecord>>asList(com.currant.jooq.Keys.PROFILE_SPORT_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileSportRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileSportRecord, ?>>asList(com.currant.jooq.Keys.PROFILE_SPORT__PROFILE_SPORT_PROFILE_ID_FKEY, com.currant.jooq.Keys.PROFILE_SPORT__PROFILE_SPORT_SPORT_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.ProfileSport as(java.lang.String alias) {
		return new com.currant.jooq.tables.ProfileSport(alias);
	}
}
