/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sport extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.SportRecord> {

	private static final long serialVersionUID = -327287052;

	/**
	 * The singleton instance of <code>public.sport</code>
	 */
	public static final com.currant.jooq.tables.Sport SPORT = new com.currant.jooq.tables.Sport();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.SportRecord> getRecordType() {
		return com.currant.jooq.tables.records.SportRecord.class;
	}

	/**
	 * The column <code>public.sport.sport_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.Long> SPORT_ID = createField("sport_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.sport.label</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>public.sport.description</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(140), this);

	/**
	 * The column <code>public.sport.image_url</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this);

	/**
	 * The column <code>public.sport.min_players</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.Integer> MIN_PLAYERS = createField("min_players", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.sport.max_players</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.Integer> MAX_PLAYERS = createField("max_players", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.sport.wait_list_amount</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.Integer> WAIT_LIST_AMOUNT = createField("wait_list_amount", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.sport.active</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportRecord, java.lang.Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.sport</code> table reference
	 */
	public Sport() {
		super("sport", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.sport</code> table reference
	 */
	public Sport(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.Sport.SPORT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.currant.jooq.tables.records.SportRecord, java.lang.Long> getIdentity() {
		return com.currant.jooq.Keys.IDENTITY_SPORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.currant.jooq.tables.records.SportRecord> getPrimaryKey() {
		return com.currant.jooq.Keys.SPORT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.SportRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.SportRecord>>asList(com.currant.jooq.Keys.SPORT_PKEY, com.currant.jooq.Keys.SPORT_LABEL_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.Sport as(java.lang.String alias) {
		return new com.currant.jooq.tables.Sport(alias);
	}
}
