/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportEquipment extends org.jooq.impl.TableImpl<com.currant.jooq.tables.records.SportEquipmentRecord> {

	private static final long serialVersionUID = -759707430;

	/**
	 * The singleton instance of <code>public.sport_equipment</code>
	 */
	public static final com.currant.jooq.tables.SportEquipment SPORT_EQUIPMENT = new com.currant.jooq.tables.SportEquipment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.currant.jooq.tables.records.SportEquipmentRecord> getRecordType() {
		return com.currant.jooq.tables.records.SportEquipmentRecord.class;
	}

	/**
	 * The column <code>public.sport_equipment.sport_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportEquipmentRecord, java.lang.Long> SPORT_ID = createField("sport_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.sport_equipment.equipment_id</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportEquipmentRecord, java.lang.Long> EQUIPMENT_ID = createField("equipment_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>public.sport_equipment.sort_order</code>. 
	 */
	public final org.jooq.TableField<com.currant.jooq.tables.records.SportEquipmentRecord, java.lang.Integer> SORT_ORDER = createField("sort_order", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.sport_equipment</code> table reference
	 */
	public SportEquipment() {
		super("sport_equipment", com.currant.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.sport_equipment</code> table reference
	 */
	public SportEquipment(java.lang.String alias) {
		super(alias, com.currant.jooq.Public.PUBLIC, com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.currant.jooq.tables.records.SportEquipmentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.currant.jooq.tables.records.SportEquipmentRecord>>asList(com.currant.jooq.Keys.SPORT_EQUIPMENT_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.currant.jooq.tables.records.SportEquipmentRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.currant.jooq.tables.records.SportEquipmentRecord, ?>>asList(com.currant.jooq.Keys.SPORT_EQUIPMENT__SPORT_EQUIPMENT_SPORT_ID_FKEY, com.currant.jooq.Keys.SPORT_EQUIPMENT__SPORT_EQUIPMENT_EQUIPMENT_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.currant.jooq.tables.SportEquipment as(java.lang.String alias) {
		return new com.currant.jooq.tables.SportEquipment(alias);
	}
}
