
- name: Install basic packages
  action: apt pkg={{ item }} state=installed update_cache=yes
  with_items:
    - nginx

- name: Set up nginx default site
  template: src=sneekyv2-api dest=/opt/sneekyv2/sneekyv2-api owner={{ sneekyv2UID }} group={{ sneekyv2GID }} mode=644

- name: enable the sneekyv2-api site
  file: src=/opt/sneekyv2/sneekyv2-api dest=/etc/nginx/sites-enabled/sneekyv2-api state=link

- name: Make sure the /opt/sneekyv2/certificates directory exists
  file: dest=/opt/sneekyv2/certificates mode=755 state=directory owner={{ sneekyv2UID }} group={{ sneekyv2GID }}

- name: Make sure the /opt/sneekyv2/logs directory exists
  file: dest=/opt/sneekyv2/logs mode=755 state=directory owner={{ sneekyv2UID }} group={{ sneekyv2GID }}


- name: Copy sneekyv2 SSL cert
  copy: src=sneekyv2.crt dest=/opt/sneekyv2/certificates/sneekyv2.crt

- name: Copy sneekyv2 SSL key
  copy: src=sneekyv2.key dest=/opt/sneekyv2/certificates/sneekyv2.key

- name: restart nginx
  service: name=nginx state=restarted