/**
 * This class is generated by jOOQ
 */
package com.currant.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.currant.jooq.tables.records.ClubRecord, java.lang.Long> IDENTITY_CLUB = Identities0.IDENTITY_CLUB;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.ClubIconRecord, java.lang.Long> IDENTITY_CLUB_ICON = Identities0.IDENTITY_CLUB_ICON;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.Long> IDENTITY_CLUB_WALL_POST = Identities0.IDENTITY_CLUB_WALL_POST;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.Long> IDENTITY_CURRANT_USER = Identities0.IDENTITY_CURRANT_USER;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.EquipmentRecord, java.lang.Long> IDENTITY_EQUIPMENT = Identities0.IDENTITY_EQUIPMENT;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.GameRecord, java.lang.Long> IDENTITY_GAME = Identities0.IDENTITY_GAME;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.ProfileRecord, java.lang.Long> IDENTITY_PROFILE = Identities0.IDENTITY_PROFILE;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.PushNotificationIdentifierRecord, java.lang.Long> IDENTITY_PUSH_NOTIFICATION_IDENTIFIER = Identities0.IDENTITY_PUSH_NOTIFICATION_IDENTIFIER;
	public static final org.jooq.Identity<com.currant.jooq.tables.records.SportRecord, java.lang.Long> IDENTITY_SPORT = Identities0.IDENTITY_SPORT;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubRecord> CLUB_PKEY = UniqueKeys0.CLUB_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubRecord> CLUB_LABEL_UNIQUE = UniqueKeys0.CLUB_LABEL_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubIconRecord> CLUB_ICON_PKEY = UniqueKeys0.CLUB_ICON_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubIconRecord> CLUB_ICON_IMAGE_URL_UNIQUE = UniqueKeys0.CLUB_ICON_IMAGE_URL_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubImageRecord> CLUB_IMAGE_UNIQUE = UniqueKeys0.CLUB_IMAGE_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubProfileConnectionRecord> CLUB_PROFILE_CONNECTION_UNIQUE = UniqueKeys0.CLUB_PROFILE_CONNECTION_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubSportRecord> CLUB_SPORT_UNIQUE = UniqueKeys0.CLUB_SPORT_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubWallPostRecord> CLUB_WALL_POST_PKEY = UniqueKeys0.CLUB_WALL_POST_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ConnectionRecord> CONNECTION_UNIQUE = UniqueKeys0.CONNECTION_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.CurrantUserRecord> CURRANT_USER_PKEY = UniqueKeys0.CURRANT_USER_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.CurrantUserRecord> USER_EMAIL_ADDRESS_UNIQUE = UniqueKeys0.USER_EMAIL_ADDRESS_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.EquipmentRecord> EQUIPMENT_PKEY = UniqueKeys0.EQUIPMENT_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.EquipmentRecord> EQUIPMENT_LABEL_UNIQUE = UniqueKeys0.EQUIPMENT_LABEL_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameRecord> GAME_PKEY = UniqueKeys0.GAME_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameEquipmentRecord> GAME_EQUIPMENT_UNIQUE = UniqueKeys0.GAME_EQUIPMENT_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameImageRecord> GAME_IMAGE_UNIQUE = UniqueKeys0.GAME_IMAGE_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileConnectionRecord> GAME_PROFILE_CONNECTION_UNIQUE = UniqueKeys0.GAME_PROFILE_CONNECTION_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileStarredRecord> GAME_PROFILE_STARRED_UNIQUE = UniqueKeys0.GAME_PROFILE_STARRED_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ProfileRecord> PROFILE_PKEY = UniqueKeys0.PROFILE_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ProfileSportRecord> PROFILE_SPORT_UNIQUE = UniqueKeys0.PROFILE_SPORT_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.PushNotificationIdentifierRecord> PUSH_NOTIFICATION_IDENTIFIER_PKEY = UniqueKeys0.PUSH_NOTIFICATION_IDENTIFIER_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.PushNotificationIdentifierRecord> PUSH_NOTIFICATION_IDENTIFIER_UNIQUE = UniqueKeys0.PUSH_NOTIFICATION_IDENTIFIER_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.SportRecord> SPORT_PKEY = UniqueKeys0.SPORT_PKEY;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.SportRecord> SPORT_LABEL_UNIQUE = UniqueKeys0.SPORT_LABEL_UNIQUE;
	public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.SportEquipmentRecord> SPORT_EQUIPMENT_UNIQUE = UniqueKeys0.SPORT_EQUIPMENT_UNIQUE;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubImageRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_IMAGE__CLUB_IMAGE_CLUB_ID_FKEY = ForeignKeys0.CLUB_IMAGE__CLUB_IMAGE_CLUB_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubProfileConnectionRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_PROFILE_CONNECTION__CLUB_PROFILE_CONNECTION_CLUB_ID_FKEY = ForeignKeys0.CLUB_PROFILE_CONNECTION__CLUB_PROFILE_CONNECTION_CLUB_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubProfileConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> CLUB_PROFILE_CONNECTION__CLUB_PROFILE_CONNECTION_PROFILE_ID_FKEY = ForeignKeys0.CLUB_PROFILE_CONNECTION__CLUB_PROFILE_CONNECTION_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubSportRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_SPORT__CLUB_SPORT_CLUB_ID_FKEY = ForeignKeys0.CLUB_SPORT__CLUB_SPORT_CLUB_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubSportRecord, com.currant.jooq.tables.records.SportRecord> CLUB_SPORT__CLUB_SPORT_SPORT_ID_FKEY = ForeignKeys0.CLUB_SPORT__CLUB_SPORT_SPORT_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubWallPostRecord, com.currant.jooq.tables.records.ProfileRecord> CLUB_WALL_POST__CLUB_WALL_POST_AUTHOR_PROFILE_ID_FKEY = ForeignKeys0.CLUB_WALL_POST__CLUB_WALL_POST_AUTHOR_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubWallPostRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_WALL_POST__CLUB_WALL_POST_CLUB_ID_FKEY = ForeignKeys0.CLUB_WALL_POST__CLUB_WALL_POST_CLUB_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> CONNECTION__CONNECTION_SOURCE_PROFILE_ID_FKEY = ForeignKeys0.CONNECTION__CONNECTION_SOURCE_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> CONNECTION__CONNECTION_TARGET_PROFILE_ID_FKEY = ForeignKeys0.CONNECTION__CONNECTION_TARGET_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameRecord, com.currant.jooq.tables.records.SportRecord> GAME__GAME_SPORT_ID_FKEY = ForeignKeys0.GAME__GAME_SPORT_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameRecord, com.currant.jooq.tables.records.ClubRecord> GAME__GAME_CLUB_ID_FKEY = ForeignKeys0.GAME__GAME_CLUB_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, com.currant.jooq.tables.records.GameRecord> GAME_EQUIPMENT__GAME_EQUIPMENT_GAME_ID_FKEY = ForeignKeys0.GAME_EQUIPMENT__GAME_EQUIPMENT_GAME_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, com.currant.jooq.tables.records.EquipmentRecord> GAME_EQUIPMENT__GAME_EQUIPMENT_EQUIPMENT_ID_FKEY = ForeignKeys0.GAME_EQUIPMENT__GAME_EQUIPMENT_EQUIPMENT_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, com.currant.jooq.tables.records.ProfileRecord> GAME_EQUIPMENT__GAME_EQUIPMENT_CLAIMED_BY_PROFILE_ID_FKEY = ForeignKeys0.GAME_EQUIPMENT__GAME_EQUIPMENT_CLAIMED_BY_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameImageRecord, com.currant.jooq.tables.records.GameRecord> GAME_IMAGE__GAME_IMAGE_GAME_ID_FKEY = ForeignKeys0.GAME_IMAGE__GAME_IMAGE_GAME_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileConnectionRecord, com.currant.jooq.tables.records.GameRecord> GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_GAME_ID_FKEY = ForeignKeys0.GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_GAME_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_PROFILE_ID_FKEY = ForeignKeys0.GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileStarredRecord, com.currant.jooq.tables.records.GameRecord> GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_GAME_ID_FKEY = ForeignKeys0.GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_GAME_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileStarredRecord, com.currant.jooq.tables.records.ProfileRecord> GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_PROFILE_ID_FKEY = ForeignKeys0.GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileRecord, com.currant.jooq.tables.records.CurrantUserRecord> PROFILE__PROFILE_CURRANT_USER_ID_FKEY = ForeignKeys0.PROFILE__PROFILE_CURRANT_USER_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileSportRecord, com.currant.jooq.tables.records.ProfileRecord> PROFILE_SPORT__PROFILE_SPORT_PROFILE_ID_FKEY = ForeignKeys0.PROFILE_SPORT__PROFILE_SPORT_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileSportRecord, com.currant.jooq.tables.records.SportRecord> PROFILE_SPORT__PROFILE_SPORT_SPORT_ID_FKEY = ForeignKeys0.PROFILE_SPORT__PROFILE_SPORT_SPORT_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.PushNotificationIdentifierRecord, com.currant.jooq.tables.records.ProfileRecord> PUSH_NOTIFICATION_IDENTIFIER__PUSH_NOTIFICATION_IDENTIFIER_PROFILE_ID_FKEY = ForeignKeys0.PUSH_NOTIFICATION_IDENTIFIER__PUSH_NOTIFICATION_IDENTIFIER_PROFILE_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.SportEquipmentRecord, com.currant.jooq.tables.records.SportRecord> SPORT_EQUIPMENT__SPORT_EQUIPMENT_SPORT_ID_FKEY = ForeignKeys0.SPORT_EQUIPMENT__SPORT_EQUIPMENT_SPORT_ID_FKEY;
	public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.SportEquipmentRecord, com.currant.jooq.tables.records.EquipmentRecord> SPORT_EQUIPMENT__SPORT_EQUIPMENT_EQUIPMENT_ID_FKEY = ForeignKeys0.SPORT_EQUIPMENT__SPORT_EQUIPMENT_EQUIPMENT_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.currant.jooq.tables.records.ClubRecord, java.lang.Long> IDENTITY_CLUB = createIdentity(com.currant.jooq.tables.Club.CLUB, com.currant.jooq.tables.Club.CLUB.CLUB_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.ClubIconRecord, java.lang.Long> IDENTITY_CLUB_ICON = createIdentity(com.currant.jooq.tables.ClubIcon.CLUB_ICON, com.currant.jooq.tables.ClubIcon.CLUB_ICON.CLUB_ICON_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.ClubWallPostRecord, java.lang.Long> IDENTITY_CLUB_WALL_POST = createIdentity(com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST, com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.CLUB_WALL_POST_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.CurrantUserRecord, java.lang.Long> IDENTITY_CURRANT_USER = createIdentity(com.currant.jooq.tables.CurrantUser.CURRANT_USER, com.currant.jooq.tables.CurrantUser.CURRANT_USER.CURRANT_USER_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.EquipmentRecord, java.lang.Long> IDENTITY_EQUIPMENT = createIdentity(com.currant.jooq.tables.Equipment.EQUIPMENT, com.currant.jooq.tables.Equipment.EQUIPMENT.EQUIPMENT_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.GameRecord, java.lang.Long> IDENTITY_GAME = createIdentity(com.currant.jooq.tables.Game.GAME, com.currant.jooq.tables.Game.GAME.GAME_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.ProfileRecord, java.lang.Long> IDENTITY_PROFILE = createIdentity(com.currant.jooq.tables.Profile.PROFILE, com.currant.jooq.tables.Profile.PROFILE.PROFILE_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.PushNotificationIdentifierRecord, java.lang.Long> IDENTITY_PUSH_NOTIFICATION_IDENTIFIER = createIdentity(com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER, com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER.PUSH_NOTIFICATION_IDENTIFIER_ID);
		public static org.jooq.Identity<com.currant.jooq.tables.records.SportRecord, java.lang.Long> IDENTITY_SPORT = createIdentity(com.currant.jooq.tables.Sport.SPORT, com.currant.jooq.tables.Sport.SPORT.SPORT_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubRecord> CLUB_PKEY = createUniqueKey(com.currant.jooq.tables.Club.CLUB, com.currant.jooq.tables.Club.CLUB.CLUB_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubRecord> CLUB_LABEL_UNIQUE = createUniqueKey(com.currant.jooq.tables.Club.CLUB, com.currant.jooq.tables.Club.CLUB.LABEL);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubIconRecord> CLUB_ICON_PKEY = createUniqueKey(com.currant.jooq.tables.ClubIcon.CLUB_ICON, com.currant.jooq.tables.ClubIcon.CLUB_ICON.CLUB_ICON_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubIconRecord> CLUB_ICON_IMAGE_URL_UNIQUE = createUniqueKey(com.currant.jooq.tables.ClubIcon.CLUB_ICON, com.currant.jooq.tables.ClubIcon.CLUB_ICON.IMAGE_URL);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubImageRecord> CLUB_IMAGE_UNIQUE = createUniqueKey(com.currant.jooq.tables.ClubImage.CLUB_IMAGE, com.currant.jooq.tables.ClubImage.CLUB_IMAGE.CLUB_ID, com.currant.jooq.tables.ClubImage.CLUB_IMAGE.IMAGE_URL, com.currant.jooq.tables.ClubImage.CLUB_IMAGE.SORT_ORDER);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubProfileConnectionRecord> CLUB_PROFILE_CONNECTION_UNIQUE = createUniqueKey(com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION, com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION.CLUB_ID, com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION.PROFILE_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubSportRecord> CLUB_SPORT_UNIQUE = createUniqueKey(com.currant.jooq.tables.ClubSport.CLUB_SPORT, com.currant.jooq.tables.ClubSport.CLUB_SPORT.CLUB_ID, com.currant.jooq.tables.ClubSport.CLUB_SPORT.SPORT_ID, com.currant.jooq.tables.ClubSport.CLUB_SPORT.SORT_ORDER);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ClubWallPostRecord> CLUB_WALL_POST_PKEY = createUniqueKey(com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST, com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.CLUB_WALL_POST_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ConnectionRecord> CONNECTION_UNIQUE = createUniqueKey(com.currant.jooq.tables.Connection.CONNECTION, com.currant.jooq.tables.Connection.CONNECTION.SOURCE_PROFILE_ID, com.currant.jooq.tables.Connection.CONNECTION.TARGET_PROFILE_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.CurrantUserRecord> CURRANT_USER_PKEY = createUniqueKey(com.currant.jooq.tables.CurrantUser.CURRANT_USER, com.currant.jooq.tables.CurrantUser.CURRANT_USER.CURRANT_USER_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.CurrantUserRecord> USER_EMAIL_ADDRESS_UNIQUE = createUniqueKey(com.currant.jooq.tables.CurrantUser.CURRANT_USER, com.currant.jooq.tables.CurrantUser.CURRANT_USER.EMAIL_ADDRESS);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.EquipmentRecord> EQUIPMENT_PKEY = createUniqueKey(com.currant.jooq.tables.Equipment.EQUIPMENT, com.currant.jooq.tables.Equipment.EQUIPMENT.EQUIPMENT_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.EquipmentRecord> EQUIPMENT_LABEL_UNIQUE = createUniqueKey(com.currant.jooq.tables.Equipment.EQUIPMENT, com.currant.jooq.tables.Equipment.EQUIPMENT.LABEL);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameRecord> GAME_PKEY = createUniqueKey(com.currant.jooq.tables.Game.GAME, com.currant.jooq.tables.Game.GAME.GAME_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameEquipmentRecord> GAME_EQUIPMENT_UNIQUE = createUniqueKey(com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT.GAME_ID, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT.EQUIPMENT_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameImageRecord> GAME_IMAGE_UNIQUE = createUniqueKey(com.currant.jooq.tables.GameImage.GAME_IMAGE, com.currant.jooq.tables.GameImage.GAME_IMAGE.GAME_ID, com.currant.jooq.tables.GameImage.GAME_IMAGE.IMAGE_URL);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileConnectionRecord> GAME_PROFILE_CONNECTION_UNIQUE = createUniqueKey(com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION, com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION.GAME_ID, com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION.PROFILE_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.GameProfileStarredRecord> GAME_PROFILE_STARRED_UNIQUE = createUniqueKey(com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED, com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED.GAME_ID, com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED.PROFILE_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ProfileRecord> PROFILE_PKEY = createUniqueKey(com.currant.jooq.tables.Profile.PROFILE, com.currant.jooq.tables.Profile.PROFILE.PROFILE_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.ProfileSportRecord> PROFILE_SPORT_UNIQUE = createUniqueKey(com.currant.jooq.tables.ProfileSport.PROFILE_SPORT, com.currant.jooq.tables.ProfileSport.PROFILE_SPORT.PROFILE_ID, com.currant.jooq.tables.ProfileSport.PROFILE_SPORT.SPORT_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.PushNotificationIdentifierRecord> PUSH_NOTIFICATION_IDENTIFIER_PKEY = createUniqueKey(com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER, com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER.PUSH_NOTIFICATION_IDENTIFIER_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.PushNotificationIdentifierRecord> PUSH_NOTIFICATION_IDENTIFIER_UNIQUE = createUniqueKey(com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER, com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER.IDENTIFIER, com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER.PLATFORM, com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER.PROFILE_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.SportRecord> SPORT_PKEY = createUniqueKey(com.currant.jooq.tables.Sport.SPORT, com.currant.jooq.tables.Sport.SPORT.SPORT_ID);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.SportRecord> SPORT_LABEL_UNIQUE = createUniqueKey(com.currant.jooq.tables.Sport.SPORT, com.currant.jooq.tables.Sport.SPORT.LABEL);
		public static final org.jooq.UniqueKey<com.currant.jooq.tables.records.SportEquipmentRecord> SPORT_EQUIPMENT_UNIQUE = createUniqueKey(com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT, com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT.SPORT_ID, com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT.EQUIPMENT_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubImageRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_IMAGE__CLUB_IMAGE_CLUB_ID_FKEY = createForeignKey(com.currant.jooq.Keys.CLUB_PKEY, com.currant.jooq.tables.ClubImage.CLUB_IMAGE, com.currant.jooq.tables.ClubImage.CLUB_IMAGE.CLUB_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubProfileConnectionRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_PROFILE_CONNECTION__CLUB_PROFILE_CONNECTION_CLUB_ID_FKEY = createForeignKey(com.currant.jooq.Keys.CLUB_PKEY, com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION, com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION.CLUB_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubProfileConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> CLUB_PROFILE_CONNECTION__CLUB_PROFILE_CONNECTION_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION, com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION.PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubSportRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_SPORT__CLUB_SPORT_CLUB_ID_FKEY = createForeignKey(com.currant.jooq.Keys.CLUB_PKEY, com.currant.jooq.tables.ClubSport.CLUB_SPORT, com.currant.jooq.tables.ClubSport.CLUB_SPORT.CLUB_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubSportRecord, com.currant.jooq.tables.records.SportRecord> CLUB_SPORT__CLUB_SPORT_SPORT_ID_FKEY = createForeignKey(com.currant.jooq.Keys.SPORT_PKEY, com.currant.jooq.tables.ClubSport.CLUB_SPORT, com.currant.jooq.tables.ClubSport.CLUB_SPORT.SPORT_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubWallPostRecord, com.currant.jooq.tables.records.ProfileRecord> CLUB_WALL_POST__CLUB_WALL_POST_AUTHOR_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST, com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.AUTHOR_PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ClubWallPostRecord, com.currant.jooq.tables.records.ClubRecord> CLUB_WALL_POST__CLUB_WALL_POST_CLUB_ID_FKEY = createForeignKey(com.currant.jooq.Keys.CLUB_PKEY, com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST, com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.CLUB_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> CONNECTION__CONNECTION_SOURCE_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.Connection.CONNECTION, com.currant.jooq.tables.Connection.CONNECTION.SOURCE_PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> CONNECTION__CONNECTION_TARGET_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.Connection.CONNECTION, com.currant.jooq.tables.Connection.CONNECTION.TARGET_PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameRecord, com.currant.jooq.tables.records.SportRecord> GAME__GAME_SPORT_ID_FKEY = createForeignKey(com.currant.jooq.Keys.SPORT_PKEY, com.currant.jooq.tables.Game.GAME, com.currant.jooq.tables.Game.GAME.SPORT_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameRecord, com.currant.jooq.tables.records.ClubRecord> GAME__GAME_CLUB_ID_FKEY = createForeignKey(com.currant.jooq.Keys.CLUB_PKEY, com.currant.jooq.tables.Game.GAME, com.currant.jooq.tables.Game.GAME.CLUB_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, com.currant.jooq.tables.records.GameRecord> GAME_EQUIPMENT__GAME_EQUIPMENT_GAME_ID_FKEY = createForeignKey(com.currant.jooq.Keys.GAME_PKEY, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT.GAME_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, com.currant.jooq.tables.records.EquipmentRecord> GAME_EQUIPMENT__GAME_EQUIPMENT_EQUIPMENT_ID_FKEY = createForeignKey(com.currant.jooq.Keys.EQUIPMENT_PKEY, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT.EQUIPMENT_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameEquipmentRecord, com.currant.jooq.tables.records.ProfileRecord> GAME_EQUIPMENT__GAME_EQUIPMENT_CLAIMED_BY_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT, com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT.CLAIMED_BY_PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameImageRecord, com.currant.jooq.tables.records.GameRecord> GAME_IMAGE__GAME_IMAGE_GAME_ID_FKEY = createForeignKey(com.currant.jooq.Keys.GAME_PKEY, com.currant.jooq.tables.GameImage.GAME_IMAGE, com.currant.jooq.tables.GameImage.GAME_IMAGE.GAME_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileConnectionRecord, com.currant.jooq.tables.records.GameRecord> GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_GAME_ID_FKEY = createForeignKey(com.currant.jooq.Keys.GAME_PKEY, com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION, com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION.GAME_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileConnectionRecord, com.currant.jooq.tables.records.ProfileRecord> GAME_PROFILE_CONNECTION__GAME_PROFILE_CONNECTION_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION, com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION.PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileStarredRecord, com.currant.jooq.tables.records.GameRecord> GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_GAME_ID_FKEY = createForeignKey(com.currant.jooq.Keys.GAME_PKEY, com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED, com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED.GAME_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.GameProfileStarredRecord, com.currant.jooq.tables.records.ProfileRecord> GAME_PROFILE_STARRED__GAME_PROFILE_STARRED_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED, com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED.PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileRecord, com.currant.jooq.tables.records.CurrantUserRecord> PROFILE__PROFILE_CURRANT_USER_ID_FKEY = createForeignKey(com.currant.jooq.Keys.CURRANT_USER_PKEY, com.currant.jooq.tables.Profile.PROFILE, com.currant.jooq.tables.Profile.PROFILE.CURRANT_USER_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileSportRecord, com.currant.jooq.tables.records.ProfileRecord> PROFILE_SPORT__PROFILE_SPORT_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.ProfileSport.PROFILE_SPORT, com.currant.jooq.tables.ProfileSport.PROFILE_SPORT.PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.ProfileSportRecord, com.currant.jooq.tables.records.SportRecord> PROFILE_SPORT__PROFILE_SPORT_SPORT_ID_FKEY = createForeignKey(com.currant.jooq.Keys.SPORT_PKEY, com.currant.jooq.tables.ProfileSport.PROFILE_SPORT, com.currant.jooq.tables.ProfileSport.PROFILE_SPORT.SPORT_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.PushNotificationIdentifierRecord, com.currant.jooq.tables.records.ProfileRecord> PUSH_NOTIFICATION_IDENTIFIER__PUSH_NOTIFICATION_IDENTIFIER_PROFILE_ID_FKEY = createForeignKey(com.currant.jooq.Keys.PROFILE_PKEY, com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER, com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER.PROFILE_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.SportEquipmentRecord, com.currant.jooq.tables.records.SportRecord> SPORT_EQUIPMENT__SPORT_EQUIPMENT_SPORT_ID_FKEY = createForeignKey(com.currant.jooq.Keys.SPORT_PKEY, com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT, com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT.SPORT_ID);
		public static final org.jooq.ForeignKey<com.currant.jooq.tables.records.SportEquipmentRecord, com.currant.jooq.tables.records.EquipmentRecord> SPORT_EQUIPMENT__SPORT_EQUIPMENT_EQUIPMENT_ID_FKEY = createForeignKey(com.currant.jooq.Keys.EQUIPMENT_PKEY, com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT, com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT.EQUIPMENT_ID);
	}
}
