/**
 * This class is generated by jOOQ
 */
package com.currant.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.club_club_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> CLUB_CLUB_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("club_club_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.club_icon_club_icon_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> CLUB_ICON_CLUB_ICON_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("club_icon_club_icon_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.club_wall_post_club_wall_post_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> CLUB_WALL_POST_CLUB_WALL_POST_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("club_wall_post_club_wall_post_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.currant_user_currant_user_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> CURRANT_USER_CURRANT_USER_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("currant_user_currant_user_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.equipment_equipment_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> EQUIPMENT_EQUIPMENT_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("equipment_equipment_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.game_game_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> GAME_GAME_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("game_game_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.profile_profile_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> PROFILE_PROFILE_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("profile_profile_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.push_notification_identifier_push_notification_identifier_i_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> PUSH_NOTIFICATION_IDENTIFIER_PUSH_NOTIFICATION_IDENTIFIER_I_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("push_notification_identifier_push_notification_identifier_i_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>public.sport_sport_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SPORT_SPORT_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("sport_sport_id_seq", com.currant.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
