/**
 * This class is generated by jOOQ
 */
package com.currant.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.club
	 */
	public static final com.currant.jooq.tables.Club CLUB = com.currant.jooq.tables.Club.CLUB;

	/**
	 * The table public.club_icon
	 */
	public static final com.currant.jooq.tables.ClubIcon CLUB_ICON = com.currant.jooq.tables.ClubIcon.CLUB_ICON;

	/**
	 * The table public.club_image
	 */
	public static final com.currant.jooq.tables.ClubImage CLUB_IMAGE = com.currant.jooq.tables.ClubImage.CLUB_IMAGE;

	/**
	 * The table public.club_profile_connection
	 */
	public static final com.currant.jooq.tables.ClubProfileConnection CLUB_PROFILE_CONNECTION = com.currant.jooq.tables.ClubProfileConnection.CLUB_PROFILE_CONNECTION;

	/**
	 * The table public.club_sport
	 */
	public static final com.currant.jooq.tables.ClubSport CLUB_SPORT = com.currant.jooq.tables.ClubSport.CLUB_SPORT;

	/**
	 * The table public.club_wall_post
	 */
	public static final com.currant.jooq.tables.ClubWallPost CLUB_WALL_POST = com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST;

	/**
	 * The table public.connection
	 */
	public static final com.currant.jooq.tables.Connection CONNECTION = com.currant.jooq.tables.Connection.CONNECTION;

	/**
	 * The table public.currant_user
	 */
	public static final com.currant.jooq.tables.CurrantUser CURRANT_USER = com.currant.jooq.tables.CurrantUser.CURRANT_USER;

	/**
	 * The table public.equipment
	 */
	public static final com.currant.jooq.tables.Equipment EQUIPMENT = com.currant.jooq.tables.Equipment.EQUIPMENT;

	/**
	 * The table public.game
	 */
	public static final com.currant.jooq.tables.Game GAME = com.currant.jooq.tables.Game.GAME;

	/**
	 * The table public.game_equipment
	 */
	public static final com.currant.jooq.tables.GameEquipment GAME_EQUIPMENT = com.currant.jooq.tables.GameEquipment.GAME_EQUIPMENT;

	/**
	 * The table public.game_image
	 */
	public static final com.currant.jooq.tables.GameImage GAME_IMAGE = com.currant.jooq.tables.GameImage.GAME_IMAGE;

	/**
	 * The table public.game_profile_connection
	 */
	public static final com.currant.jooq.tables.GameProfileConnection GAME_PROFILE_CONNECTION = com.currant.jooq.tables.GameProfileConnection.GAME_PROFILE_CONNECTION;

	/**
	 * The table public.game_profile_starred
	 */
	public static final com.currant.jooq.tables.GameProfileStarred GAME_PROFILE_STARRED = com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED;

	/**
	 * The table public.profile
	 */
	public static final com.currant.jooq.tables.Profile PROFILE = com.currant.jooq.tables.Profile.PROFILE;

	/**
	 * The table public.profile_sport
	 */
	public static final com.currant.jooq.tables.ProfileSport PROFILE_SPORT = com.currant.jooq.tables.ProfileSport.PROFILE_SPORT;

	/**
	 * The table public.push_notification_identifier
	 */
	public static final com.currant.jooq.tables.PushNotificationIdentifier PUSH_NOTIFICATION_IDENTIFIER = com.currant.jooq.tables.PushNotificationIdentifier.PUSH_NOTIFICATION_IDENTIFIER;

	/**
	 * The table public.sport
	 */
	public static final com.currant.jooq.tables.Sport SPORT = com.currant.jooq.tables.Sport.SPORT;

	/**
	 * The table public.sport_equipment
	 */
	public static final com.currant.jooq.tables.SportEquipment SPORT_EQUIPMENT = com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT;
}
