- name: Make sure the /opt/sneekyv2 directory exists
  file: dest=/opt/sneekyv2 mode=755 state=directory owner={{ sneekyv2UID }} group={{ sneekyv2GID }}

- name: Make sure the /opt/sneekyv2/logs directory exists
  file: dest=/opt/sneekyv2 mode=755 state=directory owner={{ sneekyv2UID }} group={{ sneekyv2GID }}

- name: Copy the deployable jar file to the target server
  copy: src=sneeky-v2.jar dest=/opt/sneekyv2/sneeky-v2.jar

- name: Copy the Healthcheck Script
  template: src=checkHealth.sh dest=/opt/sneekyv2/checkHealth.sh mode=0755

- name: Copy the Restart Script
  template: src=restart.sh dest=/opt/sneekyv2/restart.sh mode=0755