- name: Copy the configuration for production
  template: src=production.conf dest=/opt/sneekyv2/production.conf

- name: Copy logback xml file for production
  copy: src=logback.xml dest=/opt/sneekyv2/logback.xml

- name: Install supervisord
  easy_install: name=supervisor

- name: Initialize our supervisor directory
  file: path=/etc/supervisor owner=root group=root state=directory

- name: Fresh Supervisor sneekyv2 Conf
  copy: src=supervisord.sneekyv2.conf dest=/etc/supervisor/supervisord.sneekyv2.conf

- name: Copy the Supervisord sneekyv2 Startup Script
  copy: src=supervisord.sneekyv2 dest=/etc/init.d/supervisord.sneekyv2 mode=0755

- name: Ensure both are in default run levels
  command: update-rc.d supervisord.{{ item }} defaults
  with_items:
    - sneekyv2

- name: Kill any running sneekyv2 Supervisord scripts
  shell: kill -9 $(ps aux | grep '[s]upervisord' | grep sneekyv2 | awk '{print $2}')
  ignore_errors: yes
  sudo: True

- name: Kill any running sneekyv2 Java Processes
  shell: kill -9 $(ps aux | grep '[j]ava' | grep sneekyv2 | awk '{print $2}')
  ignore_errors: yes
  sudo: True

- name: Restart the Supervisord Script
  command: /etc/init.d/supervisord.sneekyv2 restart
