- hosts: prod
  user: ubuntu
  sudo: True
  roles:
    - ubuntu
    - deploy
    - prod-deploy
    - nginx-ssl
#    - autoscale
  vars:
      serverListenPort: "7070"
      serverListenAddress: "0.0.0.0"
      nginxProxyToAddress: "0.0.0.0"
      nginxProxyToPort: "7070"
      apiBackendDNSName: "api-v2.sneekyapp.com"
      adminContact: "aparrish@neosavvy.com"
      sneekyv2UID: "ubuntu"
      sneekyv2GID: "ubuntu"
      deploymentBranch: "master"