- hosts: staging
  remote_user: root
  roles:
    - ubuntu
    - common
    - deploy
    - nginx-ssl
  vars:
      serverListenPort: "7070"
      serverListenAddress: "0.0.0.0"
      nginxProxyToAddress: "0.0.0.0"
      nginxProxyToPort: "7070"
      apiBackendDNSName: "api.sneekyv2.neosavvy.com"
      adminContact: "aparrish@neosavvy.com"
      sneekyv2UID: "root"
      sneekyv2GID: "root"