/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubIconRecord extends org.jooq.impl.UpdatableRecordImpl<com.currant.jooq.tables.records.ClubIconRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = 58582766;

	/**
	 * Setter for <code>public.club_icon.club_icon_id</code>. 
	 */
	public void setClubIconId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.club_icon.club_icon_id</code>. 
	 */
	public java.lang.Long getClubIconId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.club_icon.image_url</code>. 
	 */
	public void setImageUrl(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.club_icon.image_url</code>. 
	 */
	public java.lang.String getImageUrl() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.club_icon.locked</code>. 
	 */
	public void setLocked(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.club_icon.locked</code>. 
	 */
	public java.lang.Boolean getLocked() {
		return (java.lang.Boolean) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.ClubIcon.CLUB_ICON.CLUB_ICON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.currant.jooq.tables.ClubIcon.CLUB_ICON.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return com.currant.jooq.tables.ClubIcon.CLUB_ICON.LOCKED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getClubIconId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getLocked();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClubIconRecord
	 */
	public ClubIconRecord() {
		super(com.currant.jooq.tables.ClubIcon.CLUB_ICON);
	}
}
