/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubRecord extends org.jooq.impl.UpdatableRecordImpl<com.currant.jooq.tables.records.ClubRecord> implements org.jooq.Record12<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = 1924265961;

	/**
	 * Setter for <code>public.club.club_id</code>. 
	 */
	public void setClubId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.club.club_id</code>. 
	 */
	public java.lang.Long getClubId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.club.label</code>. 
	 */
	public void setLabel(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.club.label</code>. 
	 */
	public java.lang.String getLabel() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.club.description</code>. 
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.club.description</code>. 
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.club.location</code>. 
	 */
	public void setLocation(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.club.location</code>. 
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.club.gps_coordinates</code>. 
	 */
	public void setGpsCoordinates(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.club.gps_coordinates</code>. 
	 */
	public java.lang.String getGpsCoordinates() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.club.club_icon</code>. 
	 */
	public void setClubIcon(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.club.club_icon</code>. 
	 */
	public java.lang.Long getClubIcon() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>public.club.club_icon_back_color</code>. 
	 */
	public void setClubIconBackColor(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.club.club_icon_back_color</code>. 
	 */
	public java.lang.Integer getClubIconBackColor() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.club.club_icon_front_color</code>. 
	 */
	public void setClubIconFrontColor(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.club.club_icon_front_color</code>. 
	 */
	public java.lang.Integer getClubIconFrontColor() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.club.visibility</code>. 
	 */
	public void setVisibility(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.club.visibility</code>. 
	 */
	public java.lang.String getVisibility() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>public.club.open_enrollment</code>. 
	 */
	public void setOpenEnrollment(java.lang.Boolean value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.club.open_enrollment</code>. 
	 */
	public java.lang.Boolean getOpenEnrollment() {
		return (java.lang.Boolean) getValue(9);
	}

	/**
	 * Setter for <code>public.club.status</code>. 
	 */
	public void setStatus(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.club.status</code>. 
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>public.club.byof</code>. 
	 */
	public void setByof(java.lang.Boolean value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.club.byof</code>. 
	 */
	public java.lang.Boolean getByof() {
		return (java.lang.Boolean) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.Club.CLUB.CLUB_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.currant.jooq.tables.Club.CLUB.LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.currant.jooq.tables.Club.CLUB.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.currant.jooq.tables.Club.CLUB.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.currant.jooq.tables.Club.CLUB.GPS_COORDINATES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.currant.jooq.tables.Club.CLUB.CLUB_ICON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.currant.jooq.tables.Club.CLUB.CLUB_ICON_BACK_COLOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.currant.jooq.tables.Club.CLUB.CLUB_ICON_FRONT_COLOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.currant.jooq.tables.Club.CLUB.VISIBILITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field10() {
		return com.currant.jooq.tables.Club.CLUB.OPEN_ENROLLMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.currant.jooq.tables.Club.CLUB.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field12() {
		return com.currant.jooq.tables.Club.CLUB.BYOF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getClubId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLabel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGpsCoordinates();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getClubIcon();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getClubIconBackColor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getClubIconFrontColor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getVisibility();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value10() {
		return getOpenEnrollment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value12() {
		return getByof();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClubRecord
	 */
	public ClubRecord() {
		super(com.currant.jooq.tables.Club.CLUB);
	}
}
