/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubImageRecord extends org.jooq.impl.TableRecordImpl<com.currant.jooq.tables.records.ClubImageRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1589203013;

	/**
	 * Setter for <code>public.club_image.club_id</code>. 
	 */
	public void setClubId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.club_image.club_id</code>. 
	 */
	public java.lang.Long getClubId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.club_image.image_url</code>. 
	 */
	public void setImageUrl(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.club_image.image_url</code>. 
	 */
	public java.lang.String getImageUrl() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.club_image.sort_order</code>. 
	 */
	public void setSortOrder(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.club_image.sort_order</code>. 
	 */
	public java.lang.Integer getSortOrder() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.ClubImage.CLUB_IMAGE.CLUB_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.currant.jooq.tables.ClubImage.CLUB_IMAGE.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.currant.jooq.tables.ClubImage.CLUB_IMAGE.SORT_ORDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getClubId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSortOrder();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClubImageRecord
	 */
	public ClubImageRecord() {
		super(com.currant.jooq.tables.ClubImage.CLUB_IMAGE);
	}
}
