/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubWallPostRecord extends org.jooq.impl.UpdatableRecordImpl<com.currant.jooq.tables.records.ClubWallPostRecord> implements org.jooq.Record7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Long> {

	private static final long serialVersionUID = 1371389028;

	/**
	 * Setter for <code>public.club_wall_post.club_wall_post_id</code>. 
	 */
	public void setClubWallPostId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.club_wall_post.club_wall_post_id</code>. 
	 */
	public java.lang.Long getClubWallPostId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.club_wall_post.author_profile_id</code>. 
	 */
	public void setAuthorProfileId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.club_wall_post.author_profile_id</code>. 
	 */
	public java.lang.Long getAuthorProfileId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.club_wall_post.club_id</code>. 
	 */
	public void setClubId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.club_wall_post.club_id</code>. 
	 */
	public java.lang.Long getClubId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>public.club_wall_post.text</code>. 
	 */
	public void setText(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.club_wall_post.text</code>. 
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.club_wall_post.image_url</code>. 
	 */
	public void setImageUrl(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.club_wall_post.image_url</code>. 
	 */
	public java.lang.String getImageUrl() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.club_wall_post.created</code>. 
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.club_wall_post.created</code>. 
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.club_wall_post.parent_post_id</code>. 
	 */
	public void setParentPostId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.club_wall_post.parent_post_id</code>. 
	 */
	public java.lang.Long getParentPostId() {
		return (java.lang.Long) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Long> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Long> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.CLUB_WALL_POST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.AUTHOR_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.CLUB_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST.PARENT_POST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getClubWallPostId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getAuthorProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getClubId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getParentPostId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClubWallPostRecord
	 */
	public ClubWallPostRecord() {
		super(com.currant.jooq.tables.ClubWallPost.CLUB_WALL_POST);
	}
}
