/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectionRecord extends org.jooq.impl.TableRecordImpl<com.currant.jooq.tables.records.ConnectionRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = 2025063082;

	/**
	 * Setter for <code>public.connection.source_profile_id</code>. 
	 */
	public void setSourceProfileId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.connection.source_profile_id</code>. 
	 */
	public java.lang.Long getSourceProfileId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.connection.target_profile_id</code>. 
	 */
	public void setTargetProfileId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.connection.target_profile_id</code>. 
	 */
	public java.lang.Long getTargetProfileId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.connection.status</code>. 
	 */
	public void setStatus(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.connection.status</code>. 
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.Connection.CONNECTION.SOURCE_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.currant.jooq.tables.Connection.CONNECTION.TARGET_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.currant.jooq.tables.Connection.CONNECTION.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getSourceProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTargetProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getStatus();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConnectionRecord
	 */
	public ConnectionRecord() {
		super(com.currant.jooq.tables.Connection.CONNECTION);
	}
}
