/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquipmentRecord extends org.jooq.impl.UpdatableRecordImpl<com.currant.jooq.tables.records.EquipmentRecord> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = -807883879;

	/**
	 * Setter for <code>public.equipment.equipment_id</code>. 
	 */
	public void setEquipmentId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.equipment.equipment_id</code>. 
	 */
	public java.lang.Long getEquipmentId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.equipment.label</code>. 
	 */
	public void setLabel(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.equipment.label</code>. 
	 */
	public java.lang.String getLabel() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.equipment.description</code>. 
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.equipment.description</code>. 
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.equipment.image_url</code>. 
	 */
	public void setImageUrl(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.equipment.image_url</code>. 
	 */
	public java.lang.String getImageUrl() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.equipment.active</code>. 
	 */
	public void setActive(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.equipment.active</code>. 
	 */
	public java.lang.Boolean getActive() {
		return (java.lang.Boolean) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.Equipment.EQUIPMENT.EQUIPMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.currant.jooq.tables.Equipment.EQUIPMENT.LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.currant.jooq.tables.Equipment.EQUIPMENT.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.currant.jooq.tables.Equipment.EQUIPMENT.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.currant.jooq.tables.Equipment.EQUIPMENT.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getEquipmentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLabel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getActive();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EquipmentRecord
	 */
	public EquipmentRecord() {
		super(com.currant.jooq.tables.Equipment.EQUIPMENT);
	}
}
