/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameProfileStarredRecord extends org.jooq.impl.TableRecordImpl<com.currant.jooq.tables.records.GameProfileStarredRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1367490358;

	/**
	 * Setter for <code>public.game_profile_starred.game_id</code>. 
	 */
	public void setGameId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.game_profile_starred.game_id</code>. 
	 */
	public java.lang.Long getGameId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.game_profile_starred.profile_id</code>. 
	 */
	public void setProfileId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.game_profile_starred.profile_id</code>. 
	 */
	public java.lang.Long getProfileId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED.PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getProfileId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GameProfileStarredRecord
	 */
	public GameProfileStarredRecord() {
		super(com.currant.jooq.tables.GameProfileStarred.GAME_PROFILE_STARRED);
	}
}
