/**
 * This class is generated by jOOQ
 */
package com.currant.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportEquipmentRecord extends org.jooq.impl.TableRecordImpl<com.currant.jooq.tables.records.SportEquipmentRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.Integer> {

	private static final long serialVersionUID = 1387488895;

	/**
	 * Setter for <code>public.sport_equipment.sport_id</code>. 
	 */
	public void setSportId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.sport_equipment.sport_id</code>. 
	 */
	public java.lang.Long getSportId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.sport_equipment.equipment_id</code>. 
	 */
	public void setEquipmentId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.sport_equipment.equipment_id</code>. 
	 */
	public java.lang.Long getEquipmentId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.sport_equipment.sort_order</code>. 
	 */
	public void setSortOrder(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.sport_equipment.sort_order</code>. 
	 */
	public java.lang.Integer getSortOrder() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT.SPORT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT.EQUIPMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT.SORT_ORDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getSportId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getEquipmentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSortOrder();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SportEquipmentRecord
	 */
	public SportEquipmentRecord() {
		super(com.currant.jooq.tables.SportEquipment.SPORT_EQUIPMENT);
	}
}
